name: warsawtransapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  responsive_builder: ^0.4.1

  cupertino_icons: ^1.0.2
  http: ^1.2.1
  flutter_typeahead: ^4.8.0
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  test: ^1.16.4

flutter:
  assets:
    - assets/all_busstops_info.json

  uses-material-design: true


